### ISSUE TITLE
No servers available for the provided ReadPreference! When connect remote server!

### ISSUE THREAD

**Issue by Lomect** [mongodb-labs/mongo-rust-driver-prototype#279] opened 2018-09-27 09:11 UTC
when i connect a remote mongo server i always got a error like (i connect by python is success):
```
Err(OperationError("No servers available for the provided ReadPreference."))
``` 
and my code like this:

```
let client = Client::with_uri("mongodb://user:pass@ip:port/database").unwrap();
let db = client.db("database");
```

**Comment by saghm** [comment] 2018-09-27 16:03
This appears to be a duplicate of https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/230; we don't currently have support for authentication in the URI implemented

**Closed** 2018-09-28 02:50 UTC

**Comment by jjgumucio** [comment] 2019-03-26 14:12
Hi there!

Is the authentication in the URI implemented now?

Im doing some test and, when I connect using `Client::with_uri()` with a connection string like `mongodb://<user>:<password>@<host>/test?retryWrites=true`, the `ConnectionString` detects the `username` and `password` automatically.

Do I still need to do "manual" authentication?

When I try to read from a DB, I get the `Err(OperationError("No servers available for the provided ReadPreference."))` message.

How does authentication works?

PD: I checked [#230](https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/230), and after doing `db.auth("admin", "somepwd");` I still get the same error.

**Comment by jjgumucio** [comment] 2019-04-12 19:50
@saghm Hey there! 
Any updates on this?

Any help would be really appreciated

**Comment by saghm** [comment] 2019-04-19 00:34
Hi @jjgumucio! URI authentication is still not implemented. Do you mind filing another issue for the issues you're having with the lazy authentication since this one is already closed? When you do that, if you could also provide the version of the database you're using, the type of cluster (standalone, replica set, or sharded cluster), and the authentication mechanism you're trying to use?
