### ISSUE TITLE
3.6 Change Streams

### ISSUE THREAD

**Issue by mjjansen** [mongodb-labs/mongo-rust-driver-prototype#246] opened 2017-12-18 21:54 UTC
Any rough sense of when these might be supported?  thank you!

https://docs.mongodb.com/manual/tutorial/change-streams-example/

**Comment by inv2004** [comment] 2018-07-20 19:30
Very important, because the thing would help to throw away different MQs.

**Comment by thedodd** [comment] 2018-08-04 21:59
Agreed. Definitely would be useful to have.

**Comment by thedodd** [comment] 2018-08-25 19:06
@saghm @kyeah any pointers on where to get started with implementing this???

**Comment by thedodd** [comment] 2018-12-13 16:07
Here is the spec on implementing this on the client side: https://github.com/mongodb/specifications/blob/master/source/change-streams/change-streams.rst

After giving it a read, it doesn't seem too crazy. I'll read through it again and break it down into a set of high level items which we could start implementing.

**Comment by inv2004** [comment] 2018-12-13 16:16
@thedodd 
changes streams is already implemented and work fine in mongo-rust-driver-prototype, unfortunately it has not merged into master, because some test failed on windows platform, Im trying to find the root cause, but its another problem (not very major)

**Comment by thedodd** [comment] 2018-12-14 04:05
@inv2004 awesome! Glad to hear it. Do you have a PR for it somewhere? Or just a branch in your fork or something?

**Comment by thedodd** [comment] 2018-12-14 19:38
Np I'll take a look over there `:)`

**Comment by saghm** [comment] 2019-12-19 15:33
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Closed by saghm** 2019-12-19 15:33 UTC

**Comment by saghm** [comment] 2019-12-19 15:43
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
