### ISSUE TITLE
[BUG] Authentication support is broken when using threads

### ISSUE THREAD

**Issue by Ten0** [mongodb-labs/mongo-rust-driver-prototype#271] opened 2018-08-17 00:55 UTC
It was already mentionned that when opening a server using the URI the username and password are not actually used, though parsed, and we're supposed to authenticate manually using : 
```rust
client.db("admin").auth("user", "pass").unwrap();
```
However, since the client is using a connection pool, -unless I missed something- we have no way to know on which connection we're authenticating when using several threads, resulting in an `OperationError("command insert requires authentication")`.

Support to authenticate the whole ThreadedClient instead of just one connection (so probably support for URI authentication, and using the same URI parsing everytime we open a new connexion) has to be added.

**Comment by saghm** [comment] 2018-08-21 17:35
I think this is a duplicate of #205 (see https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/205#issuecomment-298137819)

**Comment by saghm** [comment] 2019-12-19 15:35
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://blog.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Closed by saghm** 2019-12-19 15:35 UTC

**Comment by saghm** [comment] 2019-12-19 15:42
Apologies, the blog post link is this: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver
