### ISSUE TITLE
Performance is worse than terrible

### ISSUE THREAD

**Issue by inv2004** [mongodb-labs/mongo-rust-driver-prototype#277] opened 2018-09-23 02:33 UTC
mongodb = "0.3.10"

rustc --version
rustc 1.30.0-nightly (4591a245c 2018-09-22)

mongod --version
db version v4.0.2

Rust:
https://gist.github.com/inv2004/87b49ee4217872d9260e13a09e6bf524
```
$ time ./target/release/bench_mongo
real    0m44.043s
```

Go:
https://gist.github.com/inv2004/d8e397ee7d0553940b60dff7f3005540
```
$ time ./bench_mongo
real    0m0.798s
```

---added---
mongo_driver:
real 0m0.583s

**Comment by inv2004** [comment] 2018-09-23 03:16
+ mongo_driver:
real    0m0.583s

**Comment by vaffeine** [comment] 2018-09-23 23:16
I took a quick look at the problem with callgrind. The first thing that caught my eye was a huge amount of allocations caused by in bson::OrderedDocument::clone(), and then the same amount of deallocations, when OrderedDocument is dropped. In case of your gist OrderedDocument::clone() is called 9046, which results in 243000 calls to both __rust__alloc and __rust_dealloc at the bottom of the call stack. 
I was not able to try the same thing with Go, but I believe it doesn't allocate and then immediately drop document for each insert.
The other thing is that Collection::insert() itself took only 16% of total execution time. However, Cursor::query() took 59%. I am pretty new to this library and MongoDB itself, so I don't know if it is normal.
Going to take a look at Go and PyMongo to makes the difference.

**Comment by inv2004** [comment] 2018-09-24 01:05
Thank you, its s good point, because mongo_driver uses doc by ref also. Unfortunately, I do not think that these allocations is the main point, because initial problem was found in the code, which generates uniq doc's.

+ I did not makde any special benchmarks, but I see that .find in mongo_driver is even much faster than mongodb. ~5k/1sec (native) vs ~15k/1sec (WSL)

**Comment by inv2004** [comment] 2018-10-17 05:06
Would you like me to do another test without allocation?

Regards,

**Comment by athre0z** [comment] 2019-03-19 15:55
I experienced similar issues on a Linux machine and a MongoDB instance running in Docker. Interestingly, it's completely fine when the MongoDB instance is hosted on a macOS machine (in Docker as well). This is ... really weird, since Docker for macOS is using a Linux VM under the hood. It also isn't using a lot of CPU, networking or IO ... it's just magically unusable slow.

**Comment by inv2004** [comment] 2019-03-19 16:19
@athre0z 
I see the problem on Linux and Windows without any dockers.
+1 - no CPU usage - just very slow performance.

**Comment by athre0z** [comment] 2019-03-19 16:50
After a bit of `strace`ing, I think figured it out. The driver fails to set the `TCP_NODELAY`, resulting in nagel's algorithm to be used, delaying any `recvfrom` call by about 40ms. I added a call to [`set_nodelay`](https://doc.rust-lang.org/1.29.0/std/net/struct.TcpStream.html#method.set_nodelay) into the driver and now your example executes in 70ms on my machine.

I'll do a little more testing and drop a PR afterwards.

Fun side fact: I'm also using this driver to store order books. :wink:

**Comment by mjjansen** [comment] 2019-03-19 17:04
I had this problem with the pure Rust Mongo driver at the beginning of last year, but for some reason I did not have it here.  I'm sure that was the problem!

**Comment by athre0z** [comment] 2019-03-19 17:07
Alright, I dropped the PR. Let's see if we can get it merged. Development of this project seems to be a little frozen in the past months.

**Closed** 2019-03-22 19:58 UTC
