### ISSUE TITLE
[Linux] Compiling mongodb v0.2.8 yields errors

### ISSUE THREAD

**Issue by jjpe** [mongodb-labs/mongo-rust-driver-prototype#221] opened 2017-06-22 18:50 UTC
When I try to build my project (which depends on `v0.2.8` of this library) on Fedora 25, I get the following compilation errors:

````
[j@fed amplify]$ cargo build
   Compiling mongodb v0.2.8
error[E0308]: mismatched types
   --> /home/j/.cargo/registry/src/github.com-1ecc6299db9ec823/mongodb-0.2.8/src/gridfs/file.rs:592:37
    |
592 |             file.upload_date = Some(*datetime);
    |                                     ^^^^^^^^^ expected struct `chrono::DateTime`, found struct `chrono::datetime::DateTime`
    |
    = note: expected type `chrono::DateTime<chrono::UTC>`
               found type `chrono::datetime::DateTime<chrono::offset::utc::UTC>`
    = help: here are some functions which might fulfill your needs:
            - .timezone()

error[E0277]: the trait bound `bson::Bson: std::convert::From<chrono::DateTime<chrono::UTC>>` is not satisfied
   --> /home/j/.cargo/registry/src/github.com-1ecc6299db9ec823/mongodb-0.2.8/src/gridfs/file.rs:616:23
    |
616 |           let mut doc = doc! {
    |  _______________________^
617 | |             "_id" => (self.id.clone()),
618 | |             "chunkSize" => (self.chunk_size),
619 | |             "length" => (self.len),
620 | |             "md5" => (self.md5.to_owned()),
621 | |             "uploadDate" => (self.upload_date.as_ref().unwrap().clone())
622 | |         };
    | |_________^ the trait `std::convert::From<chrono::DateTime<chrono::UTC>>` is not implemented for `bson::Bson`
    |
    = help: the following implementations were found:
              <bson::Bson as std::convert::From<db::roles::Role>>
              <bson::Bson as std::convert::From<bson::oid::ObjectId>>
              <bson::Bson as std::convert::From<bson::ordered::OrderedDocument>>
              <bson::Bson as std::convert::From<u64>>
            and 16 others
    = note: required by `std::convert::From::from`
    = note: this error originates in a macro outside of the current crate

error[E0308]: mismatched types
   --> /home/j/.cargo/registry/src/github.com-1ecc6299db9ec823/mongodb-0.2.8/src/topology/monitor.rs:125:38
    |
125 |             result.local_time = Some(*datetime);
    |                                      ^^^^^^^^^ expected struct `chrono::DateTime`, found struct `chrono::datetime::DateTime`
    |
    = note: expected type `chrono::DateTime<chrono::UTC>`
               found type `chrono::datetime::DateTime<chrono::offset::utc::UTC>`
    = help: here are some functions which might fulfill your needs:
            - .timezone()

error: aborting due to previous error(s)

error: Could not compile `mongodb`.

To learn more, run the command again with --verbose.
````

I was about to try `mongodb v0.3` but unfortunately that release is borked (as well as `0.2.9`) since `chrono 0.3.1` [was yanked](https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/220).

**Comment by saghm** [comment] 2017-06-22 20:04
Thanks for reporting! I think this is a duplicate of #220, so I'm going to close this

**Closed by saghm** 2017-06-22 20:04 UTC

**Comment by vamshi9666** [comment] 2018-06-23 16:55
this still is not solved . i a, still facing this .

**Comment by kyeah** [comment] 2018-06-24 00:05
hi @vamshi9666, do you mean that you require v0.2.8, which is not buildable? we recommend upgrading to v0.3.1 at the minimum — I believe the changes are fairly minimal between 0.2 and 0.3 — but we could potentially create a v0.2.9 patch if necessary.
